### ISSUE TITLE
Not working for sub zone

### ISSUE THREAD

**Issue by EricMeallier** [Infomaniak/certbot-dns-infomaniak#37] opened 2024-07-17 10:34 UTC
**Step to reproduce**

Try to get a certificate from a delegated zone, into the same infomaniak account. For example, test.sub.domain.ch, with domain.ch and delegated zone sub.domain.ch in the same account

** Explanations**

with any documentation for domain API, I'm looking for a swagger for this domain to into account delegated_zone_id (which is returned by get method)

**Comment by reneluria** [comment] 2024-07-17 10:59
hello, 
by design it tries the "longer" domaine, so the delegated zone should be the one used

cf. https://github.com/Infomaniak/certbot-dns-infomaniak/blob/main/certbot_dns_infomaniak/dns_infomaniak.py#L185

**Comment by reneluria** [comment] 2024-07-17 11:08
my bad, it doesn't work yet for sub-zones

a public version of the domain API will be released soon

**Closed by reneluria** 2024-07-17 11:08 UTC
